# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('django_sms', 'django_sms'),
        ('core', 'core'),
        ('school', 'school'),
        ('licensing', 'licensing'),
        ('notifications', 'notifications'),
        ('backups', 'backups'),
        ('utils', 'utils'),
        ('images', 'images'),
        ('css', 'css'),
        ('js', 'js'),
        ('core/templates', 'core/templates'),
        ('licensing/templates', 'licensing/templates'),
        ('notifications/templates', 'notifications/templates'),
        ('school/templates', 'school/templates'),
        ('staticfiles', 'staticfiles'),
    ],
    hiddenimports=[
        'django',
        'django.contrib',
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django_sms.settings',
        'core',
        'school',
        'licensing',
        'notifications',
        'backups',
        'utils',
        'qrcode',
        'reportlab',
        'PIL',
        'weasyprint',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='JDHubSchoolSystem',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    version='version_info.txt',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='JDHubSchoolSystem',
)
