# Generated by Django 6.0.5 on 2026-07-28 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_google_drive_oauth_backup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['class_level', 'name']},
        ),
        migrations.AlterField(
            model_name='classteacherassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__in': ['CLASS_TEACHER', 'DOS', 'HEAD_TEACHER']}, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Legacy flag; single-school deployments always use the one school record'),
        ),
        migrations.AlterField(
            model_name='teachersubjectassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__in': ['CLASS_TEACHER', 'SUBJECT_TEACHER', 'SCHOOL_ADMIN', 'DOS', 'HEAD_TEACHER']}, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
    ]
