# Generated by Django 6.1 on 2026-08-07 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id_printed',
            field=models.BooleanField(default=False, help_text='Whether ID card has been printed'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_cards_printed', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_printed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_term_active',
            field=models.BooleanField(default=True, help_text='Whether student has returned for the current term'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_term_checked',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='term_return_status',
            field=models.CharField(choices=[('PENDING', 'Pending Return'), ('ACTIVE', 'Active'), ('NOT_RETURNED', 'Not Returned'), ('TRANSFERRED', 'Transferred'), ('LEFT', 'Left School')], default='ACTIVE', help_text='Student return status for the current term', max_length=20),
        ),
    ]
