"""Backwards-compatible entry point.

The brand icons are now generated by ``tools/generate_brand_icons.py``, which
keeps Windows, Android and the web/PWA icons in sync from one source. This
module simply forwards to it so existing callers keep working.

Run from anywhere:  python android-apk/make_icons.py
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'tools'))

from generate_brand_icons import main  # noqa: E402

if __name__ == '__main__':
    main()
    print('Android launcher icons written (legacy + adaptive).')
