# Generated by Django 6.1 on 2026-08-07 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_subject_options_and_more'),
        ('licensing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('STUDENT_CREATE', 'Student Created'), ('STUDENT_UPDATE', 'Student Updated'), ('STUDENT_DELETE', 'Student Deleted'), ('STUDENT_PROMOTE', 'Student Promoted'), ('STUDENT_ARCHIVE', 'Student Archived'), ('STUDENT_GRADUATE', 'Student Graduated'), ('FEE_PAYMENT', 'Fee Payment Recorded'), ('FEE_STRUCTURE_CREATE', 'Fee Structure Created'), ('FEE_STRUCTURE_UPDATE', 'Fee Structure Updated'), ('FEE_REFUND', 'Fee Refund Processed'), ('REPORT_GENERATE', 'Report Generated'), ('REPORT_PRINT', 'Report Printed'), ('REPORT_EXPORT', 'Report Exported'), ('REPORT_PUBLISH', 'Report Published'), ('USER_LOGIN', 'User Logged In'), ('USER_LOGOUT', 'User Logged Out'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('PASSWORD_CHANGE', 'Password Changed'), ('MARK_ENTRY', 'Marks Entered'), ('MARK_UPDATE', 'Marks Updated'), ('ATTENDANCE_MARK', 'Attendance Marked'), ('REMARK_ADDED', 'Remark Added'), ('SETTINGS_CHANGE', 'Settings Changed'), ('BACKUP_CREATE', 'Backup Created'), ('IMPORT_DATA', 'Data Imported'), ('EXPORT_DATA', 'Data Exported'), ('SESSION_TERMINATE', 'Session Terminated')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('term', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.schoolconfiguration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='licensing_a_action_21f349_idx'), models.Index(fields=['user', 'created_at'], name='licensing_a_user_id_7aae41_idx')],
            },
        ),
    ]
