# Generated by Django 6.1 on 2026-08-07 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='licenselog',
            name='feature_key',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='licenselog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='licenselog',
            name='action',
            field=models.CharField(choices=[('ACTIVATED', 'License Activated'), ('DEACTIVATED', 'License Deactivated'), ('VERIFIED', 'License Verified'), ('EXPIRED', 'License Expired'), ('FAILED', 'Activation Failed'), ('FEATURE_ACTIVATED', 'Feature Activated'), ('FEATURE_KEY_GENERATED', 'Feature Key Generated')], max_length=25),
        ),
        migrations.CreateModel(
            name='FeatureActivationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=8, unique=True)),
                ('feature', models.CharField(choices=[('PHOTO_UPLOAD', 'Photo Upload'), ('ID_GENERATOR', 'ID Card Generator'), ('PARENT_KIOSK', 'Parent Kiosk Portal'), ('PDF_PREVIEW', 'PDF Preview System'), ('BATCH_PROMOTION', 'Batch Promotion'), ('FINANCE_REPORTS', 'Finance Reports'), ('SMS_REPORTS', 'SMS/Exam Reports'), ('ATTENDANCE', 'Attendance Tracking'), ('CLOUD_SYNC', 'Cloud Synchronization'), ('ADVANCED_ANALYTICS', 'Advanced Analytics')], max_length=30)),
                ('is_used', models.BooleanField(default=False)),
                ('used_by', models.CharField(blank=True, max_length=100)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Activation Key',
                'verbose_name_plural': 'Feature Activation Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
