# Generated by Django 6.1 on 2026-08-07 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_student_id_printed_student_id_printed_by_and_more'),
        ('licensing', '0003_licenselog_feature_key_licenselog_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('checksum', models.CharField(help_text='SHA256 checksum', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PENDING_SYNC', 'Pending Sync'), ('SYNCED', 'Synced')], default='PENDING', max_length=20)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('sync_status', models.CharField(default='LOCAL', help_text='LOCAL, DRIVE, USB', max_length=20)),
                ('drive_file_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to='core.schoolconfiguration')),
            ],
            options={
                'verbose_name': 'Backup Record',
                'verbose_name_plural': 'Backup Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyRecoveryToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('challenge_code', models.CharField(help_text='Challenge code shown to user', max_length=64)),
                ('hwid', models.CharField(help_text='Hardware ID for this machine', max_length=50)),
                ('is_used', models.BooleanField(default=False)),
                ('used_by', models.CharField(blank=True, max_length=100)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_for_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emergency Recovery Token',
                'verbose_name_plural': 'Emergency Recovery Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EncryptedFeatureMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('encrypted_data', models.TextField(help_text='Base64 encoded encrypted feature matrix')),
                ('signature', models.CharField(help_text='HMAC signature for validation', max_length=128)),
                ('hwid', models.CharField(help_text='Bound Hardware ID', max_length=50)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('max_users', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_matrices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Matrix Key',
                'verbose_name_plural': 'Feature Matrix Keys',
            },
        ),
    ]
